version: '3.4'
services:
  multy-back:
    image:  multyio/backend:master
    command: ["make", "all"]
    env_file: .env
    volumes:
        - "${BACKEND_LOGS}:/go/src/github.com/Appscrunch/Multy-back/cmd/logs" 
        - "${BACKEND_CONF}:/go/src/github.com/Appscrunch/Multy-back/cmd/multy.config"
        - "${BTCD_CERT}:/go/src/github.com/Appscrunch/Multy-back/cmd/rpc.cert"
    ports:
      - "7778:7778"
      - "7780:7780"
      
