version: '3.4'
services:
  multy-back:
    image:  multyio/backend:master
    command: ["make", "all"]
    env_file: .env
    volumes:
        - "${BACKEND_LOGS}:/go/src/github.com/Appscrunch/Multy-back/cmd/logs" 
        - "${BACKEND_CONF}:/go/src/github.com/Appscrunch/Multy-back/cmd/multy.config"
        - "${BTCD_CERT}:/go/src/github.com/Appscrunch/Multy-back/cmd/rpc.cert"
    ports:
      - "7778:7778"
      - "7780:7780"
    depends_on:
      - nsq
      - nsqlookup
      - nsqadmin
      - mongodb
      - btcd-testnet
      
  mongodb:
    container_name: "mongodb"
    image: mongo:3.6.2
    env_file: .env
    command: mongod --smallfiles 
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ${MONGO_LOG_DIR}:/data/logs
    ports:
      - 27017:27017

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    env_file: .env
    environment:
      - NSQD_DATA_DIR=/data/nsqd
    volumes:
      - ${NSQD_DATA_DIR}:/data/nsqd
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 -data-path=/data

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "4171:4171"
    command: nsqadmin --lookupd-http-address=nsqlookup:4161
  
  btcd-testnet:
    image: multyio/btcd-testnet:1.0.0
    env_file: .env
    volumes:
     - "${BTCD}:/root/.btcd"
     - "${BTCCTL}:/root/.btcctl"
     - "${BTCD_CERT}:/root/rpc.cert"
     - "${BTCD_KEY}:/root/rpc.key"
     - "${BTCD_CONF}:/root/btcd.conf"
    ports:
     - 1334:1334
     - 18334:18334
