version: '3.4'
services:
  btcd-testnet:
    image: multyio/btcd-testnet:1.0.0
    env_file: .env
    volumes:
     - "${BTCD}:/root/.btcd"
     - "${BTCCTL}:/root/.btcctl"
    ports:
     - 1334:1334
     - 18334:18334
